fixtures:
  symlinks:
    "apache": "#{source_dir}"
  repositories:
    "oski":
      repo: "git://github.com/arusso/puppet-oski"
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
    "concat":
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "0.2.0"
